name: Deploy Zabbix AWS

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configura AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: Criar arquivo com chave pública
        run: echo "${{ secrets.ZABBIX_PUBLIC_KEY }}" > terraform/zabbix.pub

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform -chdir=terraform init

      # Importa keypair e security group se existirem (ignora erro se não existirem)
      - name: Terraform Import Key Pair
        run: |
          terraform -chdir=terraform import aws_key_pair.zabbix_key zabbix-key || echo "Key pair já importada ou não existe"
          # Troque o sg-xxxxxxxxxxxx pelo real
          terraform -chdir=terraform import aws_security_group.zabbix_sg sg-xxxxxxxxxxxx || echo "SG já importado ou não existe"

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
        env:
          TF_VAR_zabbix_public_key: ${{ secrets.ZABBIX_PUBLIC_KEY }}

      - name: Upload Terraform State
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: |
            terraform/terraform.tfstate
            terraform/terraform.tfstate.backup
            terraform/.terraform/
