name: Deploy Zabbix AWS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configura AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: Criar arquivo com chave pública
        run: echo "${{ secrets.ZABBIX_PUBLIC_KEY }}" > terraform/zabbix.pub

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Init Terraform
        run: terraform -chdir=terraform init

      - name: Apply Terraform
        run: terraform -chdir=terraform apply -auto-approve
        env:
          TF_VAR_zabbix_public_key: ${{ secrets.ZABBIX_PUBLIC_KEY }}
